on: [push]

jobs:
  build:
    name: Project Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x', '6.0.x',  ]
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  test:
    name: Unit Testing
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: npx playwright install-deps chromium
      - run: dotnet test
    
